#---
#kind: pipeline
#type: exec
#name: Debug
#
#platform:
#  os: darwin
#  arch: amd64
#
#steps:
#- name: build
#  commands:
## Get also miniupnp (submodule)
#  - git submodule update --init --recursive
## Set benjamin's home to have access to max-sdk
#  - export HOME=/Users/$(whoami)
## Get all homebrew installed commands (cmake)
#  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
#  - cd source
#  - cmake -B build . -DCMAKE_BUILD_TYPE=Debug
#  - cmake --build build --config Debug
#
#---
kind: pipeline
type: exec
name: Release

platform:
  os: darwin
  arch: amd64

steps:
- name: submodules
  commands:
# Get also miniupnp (submodule)
  - git submodule update --init --recursive

- name: build
  commands:
# Set benjamin's home to have access to max-sdk
  - export HOME=/Users/$(whoami)
# Get all homebrew installed commands (cmake)
  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  - cd source
# Configure & build
  - cmake -B build . -DCMAKE_BUILD_TYPE=Release
  - cmake --build build --config Release

- name: sign
  environment:
    CerticateCommonName:
      from_secret: CerticateCommonName
  commands:
  - cd source/scripts
  - ./sign-all_mac-externals.zsh

- name: dmg - notarize & staple
  environment:
    MyAppleTeam:
      from_secret: MyAppleTeam
    MyAppleID:
      from_secret: MyAppleID
    MyPassword:
      from_secret: MyPassword
    AppSpecificPassword:
      from_secret: AppSpecificPassword
  commands:
  - cd source/scripts
  - ./dmg-notarize+staple_mac-externals.zsh

- name: copy dmg
  commands:
  - cp mac_externals.notarized.dmg /Users/$(whoami)/Documents/Max\ 8/bnl.externals/mac_externals.drone_release.dmg