---
kind: pipeline
type: exec
name: Debug

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  commands:
# Get also miniupnp (submodule)
  - git submodule update --init --recursive
# Set benjamin's home to have access to max-sdk
  - export HOME=/Users/$(whoami)
# Get all homebrew installed commands (cmake)
  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  - cd source
  - cmake -B build . -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build --config Debug

---
kind: pipeline
type: exec
name: Release

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  environment:
    MyPassword:
      from_secret: MyPassword
    CerticateCommonName:
      from_secret: CerticateCommonName
    AppSpecificPasswordName:
      from_secret: AppSpecificPasswordName
  commands:
# Get also miniupnp (submodule)
  - git submodule update --init --recursive
# Set benjamin's home to have access to max-sdk
  - export HOME=/Users/$(whoami)
# Get all homebrew installed commands (cmake)
  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  - cd source
  - cmake -B build . -DCMAKE_BUILD_TYPE=Release
  - cmake --build build --config Release
# Unlock keychain
  - security unlock-keychain -p $MyPassword $HOME/Library/Keychains/login.keychain
  - ./sign-all+dmg-notarize+staple_mac-externals.zsh