kind: pipeline
type: exec
name: Debug

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  commands:
# First, get all homebrew installed commands
  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  - cmake -B build . -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build --config Debug
