kind: pipeline
type: exec
name: Debug

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  commands:
  - git submodule update --init --recursive
# Set benjamin's home to have access to max-sdk
  - export HOME=/Users/$(whoami)
# Get all homebrew installed commands
  - export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  - cd source
  - cmake -B build . -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build --config Debug
